"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Product, Service, SiteSettings } from "../catalog-data";

type Lead = { id: number; name: string; phone: string; email: string; company: string; product_interest: string; service_interest: string; source: string; content_accessed: string; status: string; created_at: string };
type Media = { id: number; filename: string; content_type: string; url: string; created_at: string };
type AdminData = { products: Product[]; services: Service[]; leads: Lead[]; media: Media[]; settings: SiteSettings };
type Tab = "Dashboard" | "Products" | "Services" | "Media Library" | "Leads" | "Calendly" | "Lead Form" | "Website Settings";

const nav: Array<[Tab, string]> = [["Dashboard", "⌂"], ["Products", "◇"], ["Services", "◫"], ["Media Library", "▣"], ["Leads", "◎"], ["Calendly", "□"], ["Lead Form", "≡"], ["Website Settings", "⚙"]];

export default function AdminClient({ user }: { user: { name: string; email: string } }) {
  const [tab, setTab] = useState<Tab>("Dashboard");
  const [data, setData] = useState<AdminData | null>(null);
  const [editingProduct, setEditingProduct] = useState<Partial<Product> | null>(null);
  const [editingService, setEditingService] = useState<Partial<Service> | null>(null);
  const [notice, setNotice] = useState("");

  const load = () => fetch("/api/admin").then((r) => r.json()).then(setData);
  useEffect(() => { load(); }, []);
  const flash = (message: string) => { setNotice(message); setTimeout(() => setNotice(""), 2600); };
  async function action(payload: Record<string, unknown>) { const response = await fetch("/api/admin", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error("Action failed"); await load(); }
  if (!data) return <div className="admin-loading"><img src="/mytm-logo.svg" alt="MYTM" /><span>Preparing your experience centre…</span></div>;

  const pageTitle = tab === "Calendly" ? "Calendly & meetings" : tab;
  return <div className="admin-shell">
    <aside className="admin-sidebar"><a className="admin-brand" href="/"><img src="/mytm-logo.svg" alt="MYTM" /><span>Experience Centre</span></a><nav><small>WORKSPACE</small>{nav.slice(0, 5).map(([item, icon]) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}><i>{icon}</i>{item}{item === "Leads" && <b>{data.leads.length}</b>}</button>)}<small>CONFIGURATION</small>{nav.slice(5).map(([item, icon]) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}><i>{icon}</i>{item}</button>)}</nav><div className="admin-user"><div>{user.name.slice(0, 1).toUpperCase()}</div><span><strong>{user.name}</strong><small>{user.email}</small></span><a href="/signout-with-chatgpt?return_to=/">↗</a></div></aside>
    <main className="admin-main"><header className="admin-header"><div><small>MYTM DIGITAL EXPERIENCE CENTRE</small><h1>{pageTitle}</h1></div><div className="admin-header-actions"><a href="/" target="_blank">View live site ↗</a>{tab === "Products" && <button onClick={() => setEditingProduct({ active: true, requireLead: true, featured: false, displayOrder: data.products.length + 1 })}>+ Add product</button>}{tab === "Services" && <button onClick={() => setEditingService({ active: true, displayOrder: data.services.length + 1 })}>+ Add service</button>}</div></header>
      <div className="admin-content">
        {tab === "Dashboard" && <Dashboard data={data} onNavigate={setTab} />}
        {tab === "Products" && <ProductsTable products={data.products} onEdit={setEditingProduct} onDelete={async (id) => { if (confirm("Remove this product from the catalogue?")) { await action({ action: "deleteProduct", id }); flash("Product removed"); } }} />}
        {tab === "Services" && <ServicesTable services={data.services} onEdit={setEditingService} onDelete={async (id) => { if (confirm("Remove this service?")) { await action({ action: "deleteService", id }); flash("Service removed"); } }} />}
        {tab === "Media Library" && <MediaLibrary media={data.media} onUploaded={() => { load(); flash("File uploaded"); }} />}
        {tab === "Leads" && <LeadsTable leads={data.leads} />}
        {tab === "Calendly" && <CalendlySettings settings={data.settings} onSave={async (settings) => { await action({ action: "saveSettings", settings }); flash("Calendly settings saved"); }} />}
        {tab === "Lead Form" && <LeadFormSettings settings={data.settings} onSave={async (settings) => { await action({ action: "saveSettings", settings }); flash("Lead form updated"); }} />}
        {tab === "Website Settings" && <WebsiteSettings settings={data.settings} onSave={async (settings) => { await action({ action: "saveSettings", settings }); flash("Website settings saved"); }} />}
      </div>
    </main>
    {editingProduct && <ProductEditor product={editingProduct} media={data.media} onClose={() => setEditingProduct(null)} onSave={async (product) => { await action({ action: "saveProduct", product }); setEditingProduct(null); flash(product.id ? "Product updated" : "Product published"); }} />}
    {editingService && <ServiceEditor service={editingService} onClose={() => setEditingService(null)} onSave={async (service) => { await action({ action: "saveService", service }); setEditingService(null); flash(service.id ? "Service updated" : "Service published"); }} />}
    {notice && <div className="admin-toast">✓ {notice}</div>}
  </div>;
}

function Dashboard({ data, onNavigate }: { data: AdminData; onNavigate: (tab: Tab) => void }) {
  const stats = [["Total products", data.products.length, "+ catalogue"], ["Active services", data.services.filter((s) => s.active).length, "live now"], ["Leads captured", data.leads.length, "all sources"], ["Content files", data.media.length, "PDFs & media"]];
  const sources = useMemo(() => data.leads.reduce<Record<string, number>>((map, lead) => ({ ...map, [lead.source]: (map[lead.source] || 0) + 1 }), {}), [data.leads]);
  return <><section className="admin-welcome"><div><small>GOOD TO SEE YOU</small><h2>Your digital showroom at a glance.</h2><p>Manage catalogue content, understand prospect intent and keep every meeting path current.</p></div><div className="live-status"><span>● LIVE</span><strong>Customer experience</strong><a href="/" target="_blank">Open showroom ↗</a></div></section><div className="stat-grid">{stats.map(([label, value, note], i) => <article key={String(label)}><div className={`stat-icon si-${i}`}>{["◇", "◫", "◎", "▣"][i]}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div><div className="admin-grid"><section className="admin-panel"><div className="panel-head"><div><small>LEAD ACTIVITY</small><h3>Recent prospects</h3></div><button onClick={() => onNavigate("Leads")}>View all ↗</button></div><div className="recent-list">{data.leads.slice(0, 5).map((lead) => <div key={lead.id}><div className="lead-avatar">{lead.name.slice(0, 1)}</div><span><strong>{lead.name}</strong><small>{lead.company} · {lead.source}</small></span><time>{new Date(lead.created_at).toLocaleDateString()}</time></div>)}{!data.leads.length && <div className="admin-empty">New leads will appear here as prospects engage.</div>}</div></section><section className="admin-panel"><div className="panel-head"><div><small>LEAD SOURCES</small><h3>Conversion signals</h3></div></div><div className="source-list">{Object.entries(sources).map(([source, count]) => <div key={source}><span>{source}</span><div><i style={{ width: `${Math.min(100, count * 20)}%` }} /></div><b>{count}</b></div>)}{!Object.keys(sources).length && <div className="admin-empty">Source analytics begin with the first inquiry.</div>}</div></section></div></>;
}

function ProductsTable({ products, onEdit, onDelete }: { products: Product[]; onEdit: (p: Product) => void; onDelete: (id: number) => void }) { return <section className="admin-panel data-panel"><div className="table-tools"><label>⌕ <input placeholder="Search products…" /></label><span>{products.length} products · {products.filter((p) => p.active).length} active</span></div><div className="admin-table"><div className="table-row table-labels"><span>Product</span><span>Category</span><span>Content</span><span>Status</span><span>Order</span><span /></div>{products.map((p) => <div className="table-row" key={p.id}><span className="table-product"><i>{p.name.slice(0, 2).toUpperCase()}</i><b>{p.name}<small>{p.shortDescription}</small></b></span><span><em>{p.category}</em></span><span className="content-flags"><b className={p.pdfUrl ? "ready" : ""}>PDF</b><b className={p.videoUrl ? "ready" : ""}>VID</b></span><span><i className={p.active ? "status active" : "status"}>● {p.active ? "Active" : "Draft"}</i></span><span>#{p.displayOrder}</span><span className="row-actions"><button onClick={() => onEdit(p)}>Edit</button><button onClick={() => onDelete(p.id)}>×</button></span></div>)}</div></section>; }

function ServicesTable({ services, onEdit, onDelete }: { services: Service[]; onEdit: (s: Service) => void; onDelete: (id: number) => void }) { return <div className="admin-card-grid">{services.map((s, index) => <article className="admin-service-card" key={s.id}><div><span>0{index + 1}</span><i>{["◇", "⌁", "+", "✓"][index % 4]}</i></div><small>{s.active ? "● ACTIVE" : "○ DRAFT"}</small><h3>{s.name}</h3><p>{s.shortDescription}</p><div className="admin-tags">{s.features.slice(0, 3).map((f) => <span key={f}>{f}</span>)}</div><footer><button onClick={() => onEdit(s)}>Edit service</button><button onClick={() => onDelete(s.id)}>Remove</button></footer></article>)}</div>; }

function MediaLibrary({ media, onUploaded }: { media: Media[]; onUploaded: () => void }) { const [uploading, setUploading] = useState(false); async function upload(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setUploading(true); const response = await fetch("/api/media", { method: "POST", body: new FormData(e.currentTarget) }); setUploading(false); if (response.ok) { e.currentTarget.reset(); onUploaded(); } } return <><section className="upload-zone"><form onSubmit={upload}><div className="upload-icon">⇧</div><h3>Upload to the MYTM media library</h3><p>PDF product decks, images and videos up to 50 MB.</p><label><input type="file" name="file" accept="application/pdf,image/*,video/*" required /><span>{uploading ? "Uploading…" : "Choose file"}</span></label><button disabled={uploading}>Upload media</button></form></section><div className="media-grid">{media.map((file) => <article key={file.id}><div className="file-preview">{file.content_type.includes("pdf") ? "PDF" : file.content_type.includes("video") ? "VID" : "IMG"}</div><strong>{file.filename}</strong><small>{file.content_type}</small><div><a href={file.url} target="_blank">View ↗</a><button onClick={() => navigator.clipboard.writeText(file.url)}>Copy URL</button></div></article>)}</div></>; }

function LeadsTable({ leads }: { leads: Lead[] }) { const [query, setQuery] = useState(""); const shown = leads.filter((l) => `${l.name} ${l.company} ${l.email} ${l.product_interest}`.toLowerCase().includes(query.toLowerCase())); return <section className="admin-panel data-panel"><div className="table-tools"><label>⌕ <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search leads…" /></label><button onClick={() => downloadLeads(leads)}>Export CSV ↓</button></div><div className="admin-table leads-table"><div className="table-row table-labels"><span>Prospect</span><span>Interest</span><span>Source</span><span>Status</span><span>Date</span></div>{shown.map((lead) => <div className="table-row" key={lead.id}><span className="table-product"><i>{lead.name.slice(0, 1)}</i><b>{lead.name}<small>{lead.email}<br />{lead.phone}</small></b></span><span><strong>{lead.product_interest !== "None" ? lead.product_interest : lead.service_interest}</strong><small>{lead.company}</small></span><span>{lead.source}<small>{lead.content_accessed}</small></span><span><i className="status active">● {lead.status}</i></span><span>{new Date(lead.created_at).toLocaleDateString()}</span></div>)}</div></section>; }

function CalendlySettings({ settings, onSave }: { settings: SiteSettings; onSave: (s: SiteSettings) => void }) { const [draft, setDraft] = useState(settings); return <div className="settings-grid"><section className="settings-card"><div className="settings-title"><span>□</span><div><small>INTEGRATIONS</small><h3>Calendly connection</h3><p>One scheduling link powers every meeting CTA across the customer experience.</p></div></div><label>Calendly scheduling URL<input value={draft.calendlyUrl} onChange={(e) => setDraft({ ...draft, calendlyUrl: e.target.value })} placeholder="https://calendly.com/your-team/demo" /></label><label>Button label<input value={draft.meetingLabel} onChange={(e) => setDraft({ ...draft, meetingLabel: e.target.value })} /></label><Toggle label="Meeting CTAs" note="Show scheduling actions throughout the site" checked={draft.meetingEnabled} onChange={(meetingEnabled) => setDraft({ ...draft, meetingEnabled })} /><button className="admin-save" onClick={() => onSave(draft)}>Save integration</button></section><section className="calendar-preview"><div className="preview-label">LIVE CTA PREVIEW</div><div className="preview-site"><img src="/mytm-logo.svg" alt="" /><button>{draft.meetingLabel || "Book a Meeting"}</button></div><div className="preview-calendar"><span>31</span><h3>Your calendar opens here</h3><p>Responsive, embedded and consistent on every product and service.</p></div><small>Applied to header · product details · service details · contact · footer</small></section></div>; }

function LeadFormSettings({ settings, onSave }: { settings: SiteSettings; onSave: (s: SiteSettings) => void }) { const [draft, setDraft] = useState(settings); const config = draft.formConfig; const set = (key: keyof typeof config, value: boolean) => setDraft({ ...draft, formConfig: { ...config, [key]: value } }); return <div className="settings-grid"><section className="settings-card"><div className="settings-title"><span>≡</span><div><small>CONVERSION</small><h3>Catalogue lead form</h3><p>Choose the information customers provide before accessing gated content.</p></div></div>{[["requireName", "Full name"], ["requirePhone", "Contact number"], ["requireCompany", "Company name"], ["requireEmail", "Business email"], ["requireNotes", "Notes / customer interest"], ["showProductInterest", "Product dropdown"], ["showServiceInterest", "Services dropdown"]].map(([key, label]) => <Toggle key={key} label={label} note={key.startsWith("show") ? "Includes None and Something else options" : "Required before submission"} checked={config[key as keyof typeof config]} onChange={(value) => set(key as keyof typeof config, value)} />)}<button className="admin-save" onClick={() => onSave(draft)}>Save form settings</button></section><section className="form-preview"><small>FORM PREVIEW</small><h3>Access the Product Deck</h3><p>Enter your details to continue.</p>{["Full name *", "Contact number *", "Business email *", "Company name *", "Product interest", "Service interest", "What are you most interested in? *"].map((x) => <div key={x}>{x}</div>)}<button>View product deck ↗</button></section></div>; }

function WebsiteSettings({ settings, onSave }: { settings: SiteSettings; onSave: (s: SiteSettings) => void }) { const [draft, setDraft] = useState(settings); return <section className="settings-card wide-settings"><div className="settings-title"><span>⚙</span><div><small>GLOBAL SETTINGS</small><h3>Customer experience</h3><p>Update core brand messaging and behaviour across the showroom.</p></div></div><div className="settings-fields"><label>Hero heading<textarea rows={2} value={draft.heroHeading} onChange={(e) => setDraft({ ...draft, heroHeading: e.target.value })} /></label><label>Hero supporting text<textarea rows={3} value={draft.heroSubheading} onChange={(e) => setDraft({ ...draft, heroSubheading: e.target.value })} /></label><label>Contact email<input value={draft.contactEmail} onChange={(e) => setDraft({ ...draft, contactEmail: e.target.value })} /></label><label>Contact number<input value={draft.contactNumber} onChange={(e) => setDraft({ ...draft, contactNumber: e.target.value })} /></label></div><Toggle label="Event / kiosk mode" note="Larger, focused catalogue experience for exhibitions" checked={draft.eventMode} onChange={(eventMode) => setDraft({ ...draft, eventMode })} /><Toggle label="Welcome screen" note="Optional Discover MYTM entry screen" checked={draft.welcomeScreen} onChange={(welcomeScreen) => setDraft({ ...draft, welcomeScreen })} /><button className="admin-save" onClick={() => onSave(draft)}>Save website settings</button></section>; }

function ProductEditor({ product, media, onClose, onSave }: { product: Partial<Product>; media: Media[]; onClose: () => void; onSave: (p: Record<string, unknown>) => void }) { const [draft, setDraft] = useState({ ...product, features: product.features?.join("\n") || "", benefits: product.benefits?.join("\n") || "" }); const set = (key: string, value: unknown) => setDraft({ ...draft, [key]: value }); return <Editor title={product.id ? "Edit product" : "Add product"} eyebrow="PRODUCT MANAGEMENT" onClose={onClose}><form onSubmit={(e) => { e.preventDefault(); onSave(draft); }}><div className="editor-grid"><label>Product name<input required value={draft.name || ""} onChange={(e) => set("name", e.target.value)} /></label><label>Category<input required value={draft.category || ""} onChange={(e) => set("category", e.target.value)} /></label></div><label>Short description<textarea required rows={2} value={draft.shortDescription || ""} onChange={(e) => set("shortDescription", e.target.value)} /></label><label>Full description<textarea required rows={4} value={draft.fullDescription || ""} onChange={(e) => set("fullDescription", e.target.value)} /></label><div className="editor-grid"><label>Key features (one per line)<textarea rows={6} value={String(draft.features)} onChange={(e) => set("features", e.target.value)} /></label><label>Business benefits (one per line)<textarea rows={6} value={String(draft.benefits)} onChange={(e) => set("benefits", e.target.value)} /></label></div><div className="editor-grid"><label>Product deck PDF<select value={draft.pdfUrl || ""} onChange={(e) => set("pdfUrl", e.target.value)}><option value="">No deck selected</option>{media.filter((m) => m.content_type.includes("pdf")).map((m) => <option value={m.url} key={m.id}>{m.filename}</option>)}</select></label><label>Video URL<input value={draft.videoUrl || ""} onChange={(e) => set("videoUrl", e.target.value)} placeholder="YouTube, Vimeo or hosted video" /></label></div><div className="editor-toggles"><Toggle label="Featured product" checked={Boolean(draft.featured)} onChange={(v) => set("featured", v)} /><Toggle label="Require form before PDF" checked={Boolean(draft.requireLead)} onChange={(v) => set("requireLead", v)} /><Toggle label="Published" checked={Boolean(draft.active)} onChange={(v) => set("active", v)} /></div><label>Display order<input type="number" value={draft.displayOrder || 0} onChange={(e) => set("displayOrder", Number(e.target.value))} /></label><div className="editor-actions"><button type="button" onClick={onClose}>Cancel</button><button>Save & publish</button></div></form></Editor>; }

function ServiceEditor({ service, onClose, onSave }: { service: Partial<Service>; onClose: () => void; onSave: (s: Record<string, unknown>) => void }) { const [draft, setDraft] = useState({ ...service, features: service.features?.join("\n") || "" }); const set = (key: string, value: unknown) => setDraft({ ...draft, [key]: value }); return <Editor title={service.id ? "Edit service" : "Add service"} eyebrow="SERVICE MANAGEMENT" onClose={onClose}><form onSubmit={(e) => { e.preventDefault(); onSave(draft); }}><label>Service name<input required value={draft.name || ""} onChange={(e) => set("name", e.target.value)} /></label><label>Short description<textarea required rows={3} value={draft.shortDescription || ""} onChange={(e) => set("shortDescription", e.target.value)} /></label><label>Capabilities (one per line)<textarea rows={8} value={String(draft.features)} onChange={(e) => set("features", e.target.value)} /></label><div className="editor-grid"><label>CTA label<input value={draft.cta || ""} onChange={(e) => set("cta", e.target.value)} /></label><label>Display order<input type="number" value={draft.displayOrder || 0} onChange={(e) => set("displayOrder", Number(e.target.value))} /></label></div><Toggle label="Published" checked={Boolean(draft.active)} onChange={(v) => set("active", v)} /><div className="editor-actions"><button type="button" onClick={onClose}>Cancel</button><button>Save & publish</button></div></form></Editor>; }

function Editor({ title, eyebrow, onClose, children }: { title: string; eyebrow: string; onClose: () => void; children: React.ReactNode }) { return <div className="editor-backdrop"><aside className="editor-panel"><header><div><small>{eyebrow}</small><h2>{title}</h2></div><button onClick={onClose}>×</button></header>{children}</aside></div>; }
function Toggle({ label, note, checked, onChange }: { label: string; note?: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle-row"><span><strong>{label}</strong>{note && <small>{note}</small>}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><i /></label>; }
function downloadLeads(leads: Lead[]) { const headers = ["Name", "Phone", "Email", "Company", "Product", "Service", "Source", "Status", "Date"]; const rows = leads.map((l) => [l.name, l.phone, l.email, l.company, l.product_interest, l.service_interest, l.source, l.status, l.created_at]); const csv = [headers, ...rows].map((row) => row.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = "mytm-leads.csv"; a.click(); URL.revokeObjectURL(url); }
